project:
  type: website

website:
  title: "ANNABELLE PETHERBRIDGE"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Financial Analytics"
        href: financial-analytics.qmd
      - text: "Projects"
        href: Projects.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [flatly, theme.scss]
    toc: true

